steps:
  # Build the container image for linux/amd64 (required for Cloud Run)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform', 'linux/amd64', '-t', '${_REGISTRY_PATH}/audio-echo-server', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGISTRY_PATH}/audio-echo-server']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'audio-echo-server'
      - '--image'
      - '${_REGISTRY_PATH}/audio-echo-server'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '10'

images:
  - '${_REGISTRY_PATH}/audio-echo-server'

substitutions:
  _REGISTRY_PATH: 'YOUR_REGION-docker.pkg.dev/YOUR_PROJECT_ID/YOUR_REPOSITORY'

